apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-application
  namespace: argocd
spec:
  destination:
    namespace: argo-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-rollouts
    repoURL: http://gitlab.isc/root/argo-config.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
